### ISSUE TITLE
Mac端没有窗口弹出

### ISSUE THREAD

**Issue by Mystery00** [chi-rei-den/Localizer#22]

**Comment by Mystery00** [comment]
是否考虑一下使用跨平台的语言写界面？

**Comment by sgkoishi** [comment]
> 
> 
> 是否考虑一下使用跨平台的语言写界面？

目前正在开发游戏内界面，位于分支[`squid`](https://github.com/chi-rei-den/Localizer/tree/squid)。

**Comment by sgkoishi** [comment]
基于Squid的游戏内界面已初步完成，可以从[GitHub Actions](https://github.com/chi-rei-den/Localizer/actions?query=branch%3Asquid+is%3Asuccess)选择下载。

**Comment by Mystery00** [comment]
[client.log](https://github.com/chi-rei-den/Localizer/files/4163193/client.log)
似乎有错误

**Comment by sgkoishi** [comment]
> 
> 
> [client.log](https://github.com/chi-rei-den/Localizer/files/4163193/client.log)
> 似乎有错误

emmmm似乎并不是UI的锅？
（先摸了.jpg 感觉是有生之年

**Comment by Mystery00** [comment]
1.5版本似乎还是爆炸的……
[client.log](https://github.com/chi-rei-den/Localizer/files/4237044/client.log)

**Comment by sgkoishi** [comment]
> 
> 
> 1.5版本似乎还是爆炸的……
> [client.log](https://github.com/chi-rei-den/Localizer/files/4237044/client.log)

是的.jpg
你可以尝试切换到[一个测试修复的版本](https://github.com/chi-rei-den/Localizer/suites/474331442/artifacts/2110424)，然后打开`游戏目录/Localizer/Config.json`，将`ModListMirror, ModDownloadMirror和ModDescMirror`的第一项都改成空的`""`

~~CC @AxeelAnder ~~
