### ISSUE TITLE
模組啟用後相關問題

### ISSUE THREAD

**Issue by Nevoriez** [chi-rei-den/Localizer#54]
1.
啟用localizer模組後
模組瀏覽器不給下載 要我更新
但是我的版本是正確的
![image](https://user-images.githubusercontent.com/88361100/127954313-88b952dc-242f-4211-b48b-f94ed29a31cd.png)

2.
我之前用的時候 只要點左邊的模組 右邊通常會跑出漢化包可供下載
但是我現在不管點哪個模組都是現在右邊的畫面
![image](https://user-images.githubusercontent.com/88361100/127954363-da656693-ee32-42c5-9344-0356b368e8c0.png)

https://mirror7.sgkoi.dev/ 這個網址 我點漢化包也沒反應 其他mirror也點過了

**Comment by sgkoishi** [comment]
是的，服务器流量暂时用完了。一周后恢复。

<hr>

Duplicate of #53
