### ISSUE TITLE
macos中无法正常使用localizer加载汉化包

### ISSUE THREAD

**Issue by yintao-xu** [chi-rei-den/Localizer#57]
你好，我看到你GitHub中提到macos使用tModLoader需要安装mono，下图是我mono的版本。
![1.png](https://s2.loli.net/2022/01/03/bit5LxGJjkVewl8.png)
然后从镜像站下载了localizer，版本如下图
![2.png](https://s2.loli.net/2022/01/03/tuscfmyeapSJ7qd.png)
localizer如下图所示能正常打开，但是里面的打开文件夹按钮按了没反应，也没有生成让我放汉化包的文件夹，未能正常识别汉化包。
![3.png](https://s2.loli.net/2022/01/03/BcnF4hmfaAtKHiE.png)
我的系统是Monterey 12.01，请问有解决的办法吗？

**Comment by sgkoishi** [comment]
由于开发者都没有Mac所以不知道.jpg
不过根据 #24 里的评论所提到的，可能需要开启开发者模式
~~（不过反正这些问题在1.4应该都不会存在了，虽然还没有支持1.4但这个问题自然会消失因为不用mono了~~

**Comment by yintao-xu** [comment]
> 由于开发者都没有Mac所以不知道.jpg 不过根据#24里的评论所提到的，可能需要开启开发者模式 ~（不过反正这些问题在1.4应该都不会存在了，虽然还没有支持1.4但这个问题自然会消失因为不用mono了~

我现在打开了开发者模式，已经汉化成功了，感谢你的回复。
