### ISSUE TITLE
ldstr translation

### ISSUE THREAD

**Issue by Dan21la** [chi-rei-den/Localizer#64]
Why I don't display the translation of class damage. Well, that is, I translated it to ldstr, but the game shows the original. Is there any way to fix this?

**Comment by sgkoishi** [comment]
Which mod & method? (It's really common if it doesn't work as expected before you read the source code of the mod.)
~~Also, migration to tModLoader 1.4~~

**Comment by Dan21la** [comment]
What do you mean by method? Mod: Tremor

**Comment by sgkoishi** [comment]
There is a list of `method`s and each `method` contains several pairs of Source-Target text. Those are the underlying `string` (sequence of characters) of the mods as they were written in the code. So, it's not recommended to change `ldstr` entries unless they really know what each item means.

Some common `ldstr not working` reasons might be
* The displayed is not what you found. Same `Source` usually appears multiple times and usually in different methods. If you are not changing the right one, you may break the mod or some of its feature. Failed to load mod, biome missing, crafting recipe error, etc.
* Same `Source` string appears multiple times in the same method and got de-duplicated. You may manually copy the entry multiple times and do some swap in and out trick.

**Comment by Dan21la** [comment]
Thanks for the help. The problem is solved. And I just decided to delete the entire translation and start over from the ldstr file, where I first translated the class damage. And now everything works.
